# For Exploratory Data Analysis

In [2]:
import pandas as pd  
  
# Load the dataset  
# df = pd.read_csv('./data/resale_transactions.csv')
df = pd.read_csv('./data/resale_transactions.csv')

FileNotFoundError: [Errno 2] No such file or directory: './data/resale_transactions.csv'

In [ ]:
df

,id,month,flat_type,block,street_name,storey_range,floor_area_sqm,lease_commence_date,remaining_lease,resale_price,town_id,flatm_id,town_name,flatm_name
0,1,2018-05,5 ROOM,118,PASIR RIS ST 11,07 TO 09,123.0,1989,70 years 03 months,488000.0,17,5,PASIR RIS,Improved
1,2,2016-10,4 ROOM,101,RIVERVALE WALK,01 TO 03,100.0,1999,81,345000.0,21,8,SENGKANG,Model A
2,3,2018-10,5 ROOM,688A,CHOA CHU KANG DR,19 TO 21,110.0,2002,82 years 06 months,370000.0,9,5,CHOA CHU KANG,Improved
3,4,2015-12,4 ROOM,130,LOR AH SOO,13 TO 15,103.0,1984,67,432000.0,12,8,HOUGANG,Model A
4,5,2017-09,5 ROOM,533,SERANGOON NTH AVE 4,07 TO 09,122.0,1992,74 years 02 months,500000.0,22,5,SERANGOON,Improved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88683,39106,2017-01,5 ROOM,238,YISHUN RING RD,01 TO 03,121.0,1985,67 years 07 months,380000.0,26,5,YISHUN,Improved
88684,13297,2016-04,4 ROOM,425,SERANGOON AVE 1,10 TO 12,113.0,1989,72,626000.0,22,8,SERANGOON,Model A
88685,8230,2016-09,4 ROOM,213B,COMPASSVALE LANE,10 TO 12,95.0,2012,95,435000.0,21,13,SENGKANG,Premium Apartment
88686,956,2016-04,3 ROOM,1,MARSILING DR,10 TO 12,65.0,-1974,57,250000.0,25,5,WOODLANDS,Improved
88687,25811,2015-07,3 ROOM,37,CHAI CHEE AVE,07 TO 09,66.0,-1983,66,310000.0,2,5,BEDOK,Improved

In [ ]:
df.head()

,id,month,flat_type,block,street_name,storey_range,floor_area_sqm,lease_commence_date,remaining_lease,resale_price,town_id,flatm_id,town_name,flatm_name
0,1,2018-05,5 ROOM,118,PASIR RIS ST 11,07 TO 09,123.0,1989,70 years 03 months,488000.0,17,5,PASIR RIS,Improved
1,2,2016-10,4 ROOM,101,RIVERVALE WALK,01 TO 03,100.0,1999,81,345000.0,21,8,SENGKANG,Model A
2,3,2018-10,5 ROOM,688A,CHOA CHU KANG DR,19 TO 21,110.0,2002,82 years 06 months,370000.0,9,5,CHOA CHU KANG,Improved
3,4,2015-12,4 ROOM,130,LOR AH SOO,13 TO 15,103.0,1984,67,432000.0,12,8,HOUGANG,Model A
4,5,2017-09,5 ROOM,533,SERANGOON NTH AVE 4,07 TO 09,122.0,1992,74 years 02 months,500000.0,22,5,SERANGOON,Improved

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 88688 entries, 0 to 88687
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   88688 non-null  int64
 1   month                88688 non-null  str
 2   flat_type            88688 non-null  str
 3   block                88688 non-null  str
 4   street_name          88688 non-null  str
 5   storey_range         88688 non-null  str
 6   floor_area_sqm       88688 non-null  float64
 7   lease_commence_date  88688 non-null  int64
 8   remaining_lease      88688 non-null  str
 9   resale_price         88688 non-null  float64
 10  town_id              88688 non-null  int64
 11  flatm_id             88688 non-null  int64
 12  town_name            87905 non-null  str
 13  flatm_name           88174 non-null  str
dtypes: float64(2), int64(4), str(8)
memory usage: 9.5 MB

In [ ]:
# Detecting Missing Values

df.isnull().sum()

NameError: name 'df' is not defined